version: "3.8"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - frontend

  frontend:
    image: node:16.15.1
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    command: "yarn start"
    ports:
      - "3001:3000"
