# Base image for backend
FROM python:3.12.8 AS backend

WORKDIR /app
COPY Backend/ /app

# Build frontend React app
FROM node:16.15.1 AS frontend
WORKDIR /frontend
COPY frontend/ .
RUN yarn install && yarn run build

# Install 'serve' to serve the React build

# Final Image
FROM python:3.12.8
WORKDIR /app
COPY --from=backend /app .
COPY --from=frontend /frontend/dist ./frontend_build

ENV FLASK_ENV=production

RUN apt-get install gcc
# Install gcc, update apt-get, and install unixODBC development package
RUN apt-get update 
RUN apt-get install -y gcc 
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - 
RUN curl https://packages.microsoft.com/config/debian/11/prod.list  > /etc/apt/sources.list.d/mssql-release.list 

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash
RUN apt-get update 
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18 
RUN apt-get install -y unixodbc-dev
RUN pip install -r requirements.txt
RUN az login

# Install dependencies
RUN apt-get update && apt-get install -y gcc curl nginx

# Setup Nginx
COPY /default.conf /etc/nginx/conf.d/default.conf
RUN rm -rf /usr/share/nginx/html/* && \
    cp -r ./frontend_build/* /usr/share/nginx/html/

# Expose the ports for backend and frontend
EXPOSE 80

# Serve the React app on port 80 and Flask app on port 3000
CMD service nginx start && python server.py


