#clea

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Debug Azure Secrets
        run: |
          echo "Client ID: ${{ secrets.CLIENT_ID }}"
          echo "Tenant ID: ${{ secrets.TENANT_ID }}"

      # - name: Azure Login with Service Principal
      #   run: |
      #     az login --service-principal \
      #       -u ${{ secrets.AZURE_CLIENT_ID }} \
      #       -p ${{ secrets.CLIENT_SECRET }} \
      #       --tenant ${{ secrets.TENANT_ID }}

      # - name: Log in to Azure Container Registry
      #   run: |
      #     az acr login --name ${{ secrets.AZURE_ACR_NAME }}



#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Build and push Docker image
#         run: |
#           az login
#           az acr login --name optrecruitmentapp
#           docker buildx build --platform=linux/amd64 -t optrecruitmentapp.azurecr.io/recruitment-app-optumus:latest .   
#           docker push optrecruitmentapp.azurecr.io/recruitment-app-optumus:latest   

#       - name: Deploy to Azure Web App
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: opt-recruitment-app-web
#           images: optrecruitmentapp.azurecr.io/recruitment-app-optumus:latest


