#clea

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.AZURE_ACR_NAME }}


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        run: ls
        # run: |
        #   docker buildx build --platform=linux/amd64 -t optrecruitmentapp.azurecr.io/recruitment-app-optumus:latest .   
        #   docker push optrecruitmentapp.azurecr.io/recruitment-app-optumus:latest   

#       - name: Deploy to Azure Web App
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: opt-recruitment-app-web
#           images: optrecruitmentapp.azurecr.io/recruitment-app-optumus:latest


