# name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Build and push Docker image
#         run: |
#           az login
#           az acr login --name optrecruitmentapp
#           docker buildx build --platform=linux/amd64 -t optrecruitmentapp.azurecr.io/recruitment-app-optumus:latest .   
#           docker push optrecruitmentapp.azurecr.io/recruitment-app-optumus:latest   

#       - name: Deploy to Azure Web App
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: opt-recruitment-app-web
#           images: optrecruitmentapp.azurecr.io/recruitment-app-optumus:latest


