name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        run: |
          az acr login --name <your-acr-name>
          docker build -t <your-acr-name>.azurecr.io/my-flask-react-app:latest .
          docker push <your-acr-name>.azurecr.io/my-flask-react-app:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <your-app-name>
          images: <your-acr-name>.azurecr.io/my-flask-react-app:latest


